# Generated by Django 4.2.2 on 2023-06-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0004_alter_mebel_options_mebel_parse_datetime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mebel",
            options={
                "ordering": ["parse_datetime", "-price"],
                "verbose_name": "Мебель",
                "verbose_name_plural": "Мебель",
            },
        ),
    ]
